spring.application.name=findBugsProject
server.servlet.contextPath=/pop/dancers
jasypt.encryptor.bean=encryptorBean
encryptor.password=${encryptor.password.asia}
server.port=5432
spring.datasource.url=jdbc:postgresql://dpg-d3sh3are5dus73e4hq8g-a/dancers
spring.datasource.username=ENC(4L4m8PasA3JhB1pzoNpkawdc9DPRa5hTPSqHtlhdX/kRAGWM1R+So6Yup0Y0Nk7B)
spring.datasource.password=ENC(3HGrN/4/8KF/eZ9iFrS4ZidwhoUYZ61Vq7BTSmRrntmQOpZAWx+5BNoC8aYMj6/B8mf9kvKBEsuz30VG8jeAMrHRVmj/1a9XPMUrSY2CwPw=)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
api.github.url=https://api.github.com/
