spring.application.name=findBugsProject
server.servlet.contextPath=/pop/dancers
jasypt.encryptor.bean=encryptorBean
encryptor.password=PASSword12$%(
server.port=8087
spring.datasource.url=jdbc:postgresql://localhost:5432/dancers
spring.datasource.username=ENC(z6uprk/olSQJ2WDKEKTleCU02MxU/x419ZPlhccN94zjxef24QXqT2DPm+GPDorK)
spring.datasource.password=ENC(lH6wxjZU7B7Qy5xKfxF1RPElRLouCq7IOW1+Z6RtJLSUxo7okidQO3VCNXLQBIe56sq2Qpwv6R5mpni/mdo/Aw==)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
api.github.url=https://api.github.com/