spring.application.name=findBugsProject
server.servlet.contextPath=/pop/dancers
jasypt.encryptor.bean=encryptorBean
encryptor.password=
server.port=5432
spring.datasource.url=jdbc:postgresql://dpg-d3sh3are5dus73e4hq8g-a/dancers
spring.datasource.username=ENC(kUAnf0S4IvVi7HMcqvUfR3KG+bmjQIJr17SpPavM+q8Y4h1NE1x0MvEpJcQR5KU7)
spring.datasource.password=ENC(tCIaxO4TIMmPnzxQTFZKkwJ9igdJMzWGzFfkV8qw51I4NHcV7QsDHZUXl8FkR3AkKAkDdHPwZPmLeVGrpuAvTEs17cCu6yfVlKrt9EMOosQ=)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
api.github.url=https://api.github.com/
